on:
  workflow_run:
    workflows: ["Node.js CI Unit Test"]
    types:
      - completed
  workflow_dispatch:

name: Build and Deploy to Cloud Run

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GAR_LOCATION: us-east1 # TODO: update region of the Artifact Registry
  GKE_CLUSTER: ${{secrets.GKE_CLUSTER_NAME}}
  GKE_ZONE: us-east1   # TODO: update to cluster zone
  DEPLOYMENT_NAME: adminsys2023 # TODO: update to deployment name
  REPOSITORY: admynsys2023-artifact-registry
  IMAGE: adminsys2023-application

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Docker configuration
      run: |-
        echo ${{steps.auth.outputs.access_token}} | docker login -u oauth2accesstoken --password-stdin https://$GAR_LOCATION-docker.pkg.dev
    # Get the GKE credentials so we can deploy to the cluster
    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    # Build the Docker images
    - name: build-docker images
      run: docker-compose build
    
    #- name: Build
    #  run: |-
    #    docker build \
    #      --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA" \
    #      --build-arg GITHUB_SHA="$GITHUB_SHA" \
    #      --build-arg GITHUB_REF="$GITHUB_REF" \
      
    - name: Push Docker images to Google Container Registry (GCR)
      run: |
        for image in $(docker-compose images -q); do
          docker tag $image gcr.io/{{ secrets.GCP_PROJECT_ID }}/$image
          gcloud docker -- push gcr.io/{{ secrets.GCP_PROJECT_ID }}/$image
        done

   
    # Set up kustomize
    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize
        
  
