on:
  workflow_run:
    workflows: ["Node.js CI Unit Test"]
    types:
      - completed
  workflow_dispatch:

name: Build and Deploy to Cloud Run

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: docker-compose -f docker-compose.yaml build

    - name: Authentication with GCR
      run: echo "${{secrets.GCP_ENCRYPTED_KEY}}" > key.json && gcloud auth activate-service-account --key-file=key.json

    - name: Build an push Docker Images
      run: |
        echo "${{secrets.GCP_PROJECT_ID}}" > .env
        echo "${{secrets.GCP_REGION}}" >> .env
        echo "${{secrets.GCP_CLUSTER_NAME}}" >> .env      
        docker-compose -f docker-compose.yml push

    - name: Configure Kubectl
      run: |
        gcloud container clusters get-credentials ${{ secrets.GCP_CLUSTER_NAME}} --region ${{ secrets.GCP_REGION}} --project ${{secrets.GCP_PROJECT_ID}}

    - name: Apply Kubernetes configuration
      run: kubectl apply -f backend-deployment.yaml

      
